from fastapi import Depends, HTTPException, status
from fastapi.security import OAuth2PasswordBearer
from jose import JWTError, jwt
from app.core.token import SECRET_KEY, ALGORITHM
from app.db.session import get_db
from app.domain.user.repository import UserRepository
from app.domain.user.service import UserService

# ðŸ”¥ CorreÃ§Ã£o: Configurar o tokenUrl corretamente
oauth2_scheme = OAuth2PasswordBearer(tokenUrl="/api/v1/auth/token")

def get_current_user(token: str = Depends(oauth2_scheme), db=Depends(get_db)):
    credentials_exception = HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="NÃ£o foi possÃ­vel validar as credenciais",
        headers={"WWW-Authenticate": "Bearer"},
    )

    try:
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        username: str = payload.get("sub")
        if username is None:
            raise credentials_exception
    except JWTError:
        raise credentials_exception

    user_service = UserService(UserRepository(db))
    user = user_service.get_user_by_username(username)

    if user is None:
        raise credentials_exception

    return user
